[package]
name = "cw-orch-polytone"
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cw-orch = { version="0.16.4", features=["daemon"] }

polytone-note = { version = "1.0.0", path = "../../contracts/main/note" }
polytone-proxy = { version = "1.0.0", path = "../../contracts/main/proxy" }
polytone-voice = { version = "1.0.0", path = "../../contracts/main/voice" }

[dev-dependencies]
anyhow.workspace = true
