[package]
name = "cw-orch-polytone"
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow.workspace = true

#cw-orch = { version="0.16.0", features=["daemon"] }
cw-orch = { package = "cw-orch-interchain", registry = "abstract-money", features=["daemon"] }

ibc-relayer-types = "0.25.0"
polytone-note = { version = "1.0.0", path = "../../contracts/main/note" }
polytone-proxy = { version = "1.0.0", path = "../../contracts/main/proxy" }
polytone-voice = { version = "1.0.0", path = "../../contracts/main/voice" }

[dev-dependencies]
anyhow.workspace = true
env_logger = "0.10.0"
