[package]
name = "abstract-polytone"
authors = ["ekez <ekez@withoutdoing.com>"]
description = "Core interfaces for Polytone Interchain accounts and queries."
edition = { workspace = true }
license = { workspace = true }
rust-version = { workspace = true }
version = "2.0.0"

[dependencies]
cosmwasm-schema = { workspace = true }
cosmwasm-std = { workspace = true }
cw-storage-plus = { workspace = true }
thiserror = { workspace = true }
