[package]
name = "polytone"
authors = ["ekez <ekez@withoutdoing.com>"]
description = "Core interfaces for Polytone Interchain accounts and queries."
edition = { workspace = true }
license = { workspace = true }
rust-version = { workspace = true }
version = { workspace = true }

[features]
interface = ["dep:cw-orch"]

[dependencies]
cosmwasm-schema = { workspace = true }
cosmwasm-std = { workspace = true }
cw-storage-plus = { workspace = true }
thiserror = { workspace = true }
cw-orch = { git = "https://github.com/AbstractSDK/cw-orchestrator", branch = "feature/starship", version = "0.15.0", optional = true }
