[package]
name = "abstract-cw-orch-polytone"
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
version = "3.0.0"
description = "CW Orchestrator interfaces for Polytone"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

cw-orch = { workspace = true }
cosmwasm-std = { workspace = true }
polytone-note = { workspace = true }
polytone-proxy = { workspace = true }
polytone-voice = { workspace = true }
cw-orch-interchain = { workspace = true }

[dev-dependencies]
anyhow.workspace = true
